# Generated by Django 2.0 on 2019-12-04 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrapy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='名称')),
                ('url', models.CharField(default='', max_length=100, verbose_name='网址')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('scrapy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scrapy.Scrapy', verbose_name='爬虫')),
            ],
            options={
                'verbose_name': '网文分类',
                'verbose_name_plural': '网文分类',
            },
        ),
    ]
