# Generated by Django 2.1 on 2018-08-28 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloguser',
            name='userIcon',
            field=models.ImageField(default='blog/images/default_1.jpg', upload_to='blog/images'),
        ),
    ]
