# Generated by Django 2.0 on 2018-09-07 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180903_1401'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_time'], 'verbose_name_plural': '评论表'},
        ),
    ]
