# Generated by Django 2.0 on 2019-11-21 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180907_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloguser',
            name='address',
            field=models.CharField(default='上海市-闸北区', max_length=20, verbose_name='地址'),
        ),
        migrations.AddField(
            model_name='bloguser',
            name='email',
            field=models.CharField(default='602387134@qq.com', max_length=20, verbose_name='邮箱'),
        ),
        migrations.AddField(
            model_name='bloguser',
            name='professional',
            field=models.CharField(default='ios开发工程师', max_length=20, verbose_name='职业'),
        ),
        migrations.AddField(
            model_name='bloguser',
            name='sign',
            field=models.CharField(default='昆仑剑出血汪洋，千里直驱黄河黄', max_length=20, verbose_name='签名'),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_comment', to='blog.Comment', verbose_name='所属评论或回复'),
        ),
        migrations.AddField(
            model_name='comment',
            name='reply_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='blog.BlogUser', verbose_name='被回复用户'),
        ),
        migrations.AddField(
            model_name='comment',
            name='root',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='root_comment', to='blog.Comment', verbose_name='顶级评论'),
        ),
        migrations.AlterField(
            model_name='bloguser',
            name='account',
            field=models.CharField(max_length=20, unique=True, verbose_name='账号'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='blog.BlogUser', verbose_name='评论用户'),
        ),
    ]
